blank_issues_enabled: false
contact_links:
  - name: Repository Security Issues, Bug Reports, Feature Requests, and General Inquiries
    url: mailto:site-admin@monsterspawned.studio?subject=Repository%20Inquiries&body=Please%20report%20security%20vulnerabilities,%20bugs,%20feature%20requests,%20or%20ask%20general%20inquiries%20here.
    about: Please report security vulnerabilities, bugs, feature requests, or ask general inquiries here.
